import { c as create_ssr_component } from "../../../chunks/ssr.js";
const css = {
  code: ".rubiks-cube.svelte-2uekd5{width:300px;height:300px;margin:0 auto;border:1px solid #ccc;position:relative;perspective:1000px;transform-style:preserve-3d}.rubiks-cube-face.svelte-2uekd5{width:100px;height:100px;position:absolute;background-color:#fff;border:1px solid #ccc}.rubiks-cube-face.front.svelte-2uekd5{transform:translateZ(-50px)}.rubiks-cube-face.back.svelte-2uekd5{transform:translateZ(50px) rotateY(180deg)}.rubiks-cube-face.left.svelte-2uekd5{transform:translateX(-50px) rotateY(-90deg)}.rubiks-cube-face.right.svelte-2uekd5{transform:translateX(50px) rotateY(90deg)}.rubiks-cube-face.top.svelte-2uekd5{transform:translateY(-50px) rotateX(90deg)}.rubiks-cube-face.bottom.svelte-2uekd5{transform:translateY(50px) rotateX(-90deg)}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["\\n\\n<style>\\n.rubiks-cube {\\n  width: 300px;\\n  height: 300px;\\n  margin: 0 auto;\\n  border: 1px solid #ccc;\\n  position: relative;\\n  perspective: 1000px;\\n  transform-style: preserve-3d;\\n}\\n\\n.rubiks-cube-face {\\n  width: 100px;\\n  height: 100px;\\n  position: absolute;\\n  background-color: #fff;\\n  border: 1px solid #ccc;\\n}\\n\\n.rubiks-cube-face.front {\\n  transform: translateZ(-50px);\\n}\\n\\n.rubiks-cube-face.back {\\n  transform: translateZ(50px) rotateY(180deg);\\n}\\n\\n.rubiks-cube-face.left {\\n  transform: translateX(-50px) rotateY(-90deg);\\n}\\n\\n.rubiks-cube-face.right {\\n  transform: translateX(50px) rotateY(90deg);\\n}\\n\\n.rubiks-cube-face.top {\\n  transform: translateY(-50px) rotateX(90deg);\\n}\\n\\n.rubiks-cube-face.bottom {\\n  transform: translateY(50px) rotateX(-90deg);\\n}\\n</style>\\n\\n<script>\\nimport { onMount } from \'svelte\';\\n\\tonMount(async () => {\\nconst rubiksCube = document.querySelector(\'.rubiks-cube\');\\nconst faces = document.querySelectorAll(\'.rubiks-cube-face\');\\n\\nlet angle = 0;\\n\\nfunction rotateCube() {\\n  angle += 1;\\n  rubiksCube.style.transform = `rotateY(${angle}deg)`;\\n\\n  for (const face of faces) {\\n    const faceAngle = angle * (Number(face.dataset.angle) / 90);\\n    face.style.transform = `rotateZ(${faceAngle}deg)`;\\n  }\\n\\n  requestAnimationFrame(rotateCube);\\n}\\n\\nrotateCube();\\n    });\\n<\/script>\\n<div class=\\"rubiks-cube\\">\\n    <div class=\\"rubiks-cube-face front\\">Front</div>\\n    <div class=\\"rubiks-cube-face back\\">Back</div>\\n    <div class=\\"rubiks-cube-face left\\">Left</div>\\n    <div class=\\"rubiks-cube-face right\\">Right</div>\\n    <div class=\\"rubiks-cube-face top\\">Top</div>\\n    <div class=\\"rubiks-cube-face bottom\\">Bottom</div>\\n  </div>\\n\\n  "],"names":[],"mappings":"AAGA,0BAAa,CACX,KAAK,CAAE,KAAK,CACZ,MAAM,CAAE,KAAK,CACb,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,MAAM,CAAE,GAAG,CAAC,KAAK,CAAC,IAAI,CACtB,QAAQ,CAAE,QAAQ,CAClB,WAAW,CAAE,MAAM,CACnB,eAAe,CAAE,WACnB,CAEA,+BAAkB,CAChB,KAAK,CAAE,KAAK,CACZ,MAAM,CAAE,KAAK,CACb,QAAQ,CAAE,QAAQ,CAClB,gBAAgB,CAAE,IAAI,CACtB,MAAM,CAAE,GAAG,CAAC,KAAK,CAAC,IACpB,CAEA,iBAAiB,oBAAO,CACtB,SAAS,CAAE,WAAW,KAAK,CAC7B,CAEA,iBAAiB,mBAAM,CACrB,SAAS,CAAE,WAAW,IAAI,CAAC,CAAC,QAAQ,MAAM,CAC5C,CAEA,iBAAiB,mBAAM,CACrB,SAAS,CAAE,WAAW,KAAK,CAAC,CAAC,QAAQ,MAAM,CAC7C,CAEA,iBAAiB,oBAAO,CACtB,SAAS,CAAE,WAAW,IAAI,CAAC,CAAC,QAAQ,KAAK,CAC3C,CAEA,iBAAiB,kBAAK,CACpB,SAAS,CAAE,WAAW,KAAK,CAAC,CAAC,QAAQ,KAAK,CAC5C,CAEA,iBAAiB,qBAAQ,CACvB,SAAS,CAAE,WAAW,IAAI,CAAC,CAAC,QAAQ,MAAM,CAC5C"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div class="rubiks-cube svelte-2uekd5" data-svelte-h="svelte-1b0c0t1"><div class="rubiks-cube-face front svelte-2uekd5">Front</div> <div class="rubiks-cube-face back svelte-2uekd5">Back</div> <div class="rubiks-cube-face left svelte-2uekd5">Left</div> <div class="rubiks-cube-face right svelte-2uekd5">Right</div> <div class="rubiks-cube-face top svelte-2uekd5">Top</div> <div class="rubiks-cube-face bottom svelte-2uekd5">Bottom</div></div>`;
});
export {
  Page as default
};
